# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33eb08b50bd444fdaf8b3d22b45f8566540a7cdb52ebcd410f3702b445217c00550bdad39e0bf201f11d186fa991467652b840285fbfc52f9c4ecd4ce181e85a

test:
  secret_key_base: 9a91ed4e331026ed5a6e78ad43763d749a5d58527614c79954a8f50cead10d68250010ffbc30246d5346a185c6a83337bfd7ddc92f7d4ddd6c9deb4555fed960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
